spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:aprendendowebflux}:${DB_PASSWORD}@aprendendowebfluxcluste.jpduzm0.mongodb.net/aprendendo-webflux?retryWrites=true&w=majority&appName=AprendendoWebfluxCluster
  application:
    name: aprendendo-webflux