spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@aprendendowebfluxcluste.jpduzm0.mongodb.net/${DB_NAME}?retryWrites=true&w=majority&appName=${DB_CLUSTER}
      auto-index-creation: true
  application:
    name: aprendendo-webflux